### ISSUE TITLE
tag-like search for items without markdown notes

### ISSUE THREAD

**Issue by notuntoward** [daeh/zotero-markdb-connect#140]
During a long literature search session, I often add a lot of new zotero bibliography items in one shot.  But later, when I go back to add the corresponding obsidian notes, I cannot find those new items, the ones I haven't yet obsidianized.

Would it be possible to add a view which filters out items that already have obsidian notes, and shows only those that don't?  I mean something that looks like the `todo` tag search in the screenshot below.

I know that I could add a literal tag like `doesn't have obsidian note` every time I create a new item, but this wouldn't take advantage of `markdb-connect'`s carefree automatic obsidian note search.  Also, I've tried this already, and found myself constantly forgetting to add or remove such tags.  In fact, this is what drove me to `markdb-connect', which I really like, and use nearly every day.

![image](https://github.com/user-attachments/assets/5998dab6-df71-4114-a725-c22698e7b4b0)

**Comment by notuntoward** [comment]
That does seem like it should work, but the `does not contain` search doesn't exclude the items with an obsidian note.  Maybe it's a Zotero 7 bug?

In the example below, my custom tag is `obsLitNote`, and the paper, "A Data-driven Method for Adaptive Reserve Requirement Estimation via Probabilistic Net Load Forecasting" has an obsidian note.

Here's the `does not contain` search`: 

![image](https://github.com/user-attachments/assets/f5d33895-0594-48d6-8288-035951f9622d)

A here's the `contains` search:

![image](https://github.com/user-attachments/assets/d5ed558a-b30e-41a8-8785-ba85300a17a4)

**Comment by daeh** [comment]
It's because you have "Search subcollections" checked. See how "A decoder-only foundation model for time-series" is greyed out but "A decoder-only foundation model for time-series" is in black? That's telling you that "A decoder-only foundation model for time-series" doesn't match the search criteria but it's being displayed because a child of that element does. Since the "obsLitNote" tag only applies to top level items, that's all you need to search. The "subcollections" name is a bit confusing, but unchecking it will still search all the papers in your entire local DB.

**Comment by notuntoward** [comment]
Ah, I see.  Thanks very much.  Is it possible to narrow this down to the currently selectioned collection?

**Comment by daeh** [comment]
you can specify a subcollection, but I'm not sure what options exist for context-aware search. You could ask the Zotero forums. Cheers.
