### ISSUE TITLE
Zotero crashing

### ISSUE THREAD

**Issue by Kullenej** [daeh/zotero-markdb-connect#29]
Hello and thank you for a very needed add-on!

I have been using this add-on for a while, and it has been working perfectly. But recently Zotero crashed every time I tried to open it, and through some debugging with the people at the Zotero forum we finally found that the bug was within this add-on. When i removed it, Zotero could open again. I'm no programmer so will not give any tips on what needs to be done, but in the forum thread there was an advice for a line that should be removed. For further explanation see the thread here: https://forums.zotero.org/discussion/comment/417064#Comment_417064

**Comment by daeh** [comment]
Woah. Thank you for bringing this to my attention. Will you please give me your system information so that I can better understand this bug?

**Comment by daeh** [comment]
Since I haven't figured out how to reproduce this bug yet, I'd be very grateful if you are able to test whether the `0.0.19a` pre-release solves your issue:  https://github.com/daeh/zotero-markdb-connect/releases/download/v0.0.19a/MarkDBConnect-0.0.19a.xpi

**Comment by Kullenej** [comment]
It happened again as soon as I restarted Zotero with the new add-on installed

**Comment by Kullenej** [comment]
Here is the system error message I get: [System Error Message.txt](https://github.com/daeh/zotero-markdb-connect/files/9548734/System.Error.Message.txt)

**Comment by daeh** [comment]
Yes, the `0.0.19a` has the `<script src="chrome://zotero/content/include.js"/>` line in `overlay.xul` commented out. I'm not sure why that line would be suspect (and removing it is obviously not sufficient to fix the issue). I'll dig around. Thank you for the feedback on the pre-release and for the system error.

**Comment by daeh** [comment]
FYI I made another change that's related to the potential race condition, but since I haven't figured out how to reproduce this bug yet I'm shooting in the dark. 

One thing that sticks out to me in the zotero debug log that you uploaded to the BBT issue is that MarkDB-connect is raising a warning that your obsidian vault path cannot be found. That shouldn't cause a crash, but I'm wondering if it somehow related. Do you know why the vault path might not be found?

If you're up for helping me trouble shoot this some more, you can try installing the `0.0.19b` release https://github.com/daeh/zotero-markdb-connect/releases/download/v0.0.19b/MarkDBConnect-0.0.19b.xpi

and then uploading the zotero debug log here (same as you did on the BBT issue):
```sh
/Applications/Zotero.app/Contents/MacOS/zotero -ZoteroDebugText > ~/Desktop/zotero-debug-19b.txt
```

**Comment by Kullenej** [comment]
Thanks! Yes, I have sometimes changed to a new vault, and that hasn't been a problem with your add-on. Just went into settings and changed the vault path. I have probably not changed that for my latest vault. I will try to fix that as well, and also try your new release. Thank you for your effort. I will upload the debug as soon as possible!

**Comment by daeh** [comment]
Ok. Go update to the production release and if the crash comes back, just upload the zotero debug log and I'll see if I can gain any more insight into its cause. Thanks for the help troubleshooting. https://github.com/daeh/zotero-markdb-connect/releases/download/v0.0.19/MarkDBConnect-0.0.19.xpi

**Comment by daeh** [comment]
Hopefully things have been running smoothly with v0.0.19. I'm going to mark this a closed, but please reopen if the problem shows up again, @Kullenej
