### ISSUE TITLE
MarkDB not identifying YAML

### ISSUE THREAD

**Issue by PeteCT** [daeh/zotero-markdb-connect#35]
Hi - I just installed Zotero and the plug-in for use with Obsidian 1.1.9. I set everything up per instructions, specifying the file path and YAML keyword, and created a test note.

The plug-in works correctly when I include @citekey in the filename, but it is not working with I only have the citekey in YAML metadata. 

Is it possible that something is broken?  Please help!

Pete

**Comment by daeh** [comment]
Hi @PeteCT --- to avoid errors, the filer filter should only return markdown files that correspond with Zotero items. You can
(1) use a more specific regex
(2) use a file naming convention where reading notes have different file name patterns than non-reading notes
(3) keep reading notes in a different folder than non-reading notes

**Comment by daeh** [comment]
@PeteCT for instance (see \#1 and \#2 above), if your reading notes all have the filename pattern `{citekey}.md`, you could use a filefilter regex that excludes files with more than 1 word in the filename. 

But it's generally good practice to keep your reading notes in a specific folder (\#3) and have them use a specific naming convention (/#2) rather than relying on a complicated filefilter regex.

**Comment by daeh** [comment]
Hi @PeteCT — it has been a month so I'm going to close this issue, but feel free to reopen it or start a new one if you're still having trouble.
